@startuml
' skinparams begin
skinparam class {
	FontColor black
	FontSize 14
	FontName "Source Code Pro"
	BorderColor DarkKhaki
	ArrowColor DarkOrange
}

skinparam Arrow {
	FontSize 14
	FontName "Source Code Pro"
	Thickness 1.6
}
skinparam PackageFontName "Source Code Pro"
skinparam NoteBackgroundColor DarkKhaki
skinparam NoteBorderColor gray
' skinparams end

hide members


show DataMapper methods
show Repository methods


package main {
	class CLI << (S,#FF7700) System >> {
	     + displayProducts()
	}
	show CLI methods

	class StdOut << (S,#FF7700) System >>
}

interface DataMapper {
	+ retrieveAll()
}
interface Repository {
	+ findAll()
}


package "kollex.DataProvider.\nAssortment" {
    interface "Product" as ProviderProduct
}

package kollex.Export {
     interface ExportFormatter {
         + serialize()
         + setItem()
     }
      Serializable ()-- ExportFormatter
     class JsonOutput
     ExportFormatter <|.. JsonOutput
}
show ExportFormatter methods

CLI --[#6b8e23]> Repository : request\ndata
Repository -[#6b8e23]> DataMapper
DataMapper -[#6b8e23]-> ProviderProduct  : create \nDSL objects

ProviderProduct -[#6b8e23]-> JsonOutput

JsonOutput -[#6b8e23]---> StdOut : print\noutput


@enduml
